/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DataImp;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DsMonHoc;
import model.SinhVien;

/**
 *
 * @author LaptopDT
 */
public class AddSinhVienCNTT extends javax.swing.JDialog {

    private static final String currentDir = System.getProperty("user.dir");
    private static final String separator = File.separator;
    private static final String fileData = currentDir + separator + "data" + separator + "FileSV.json";
    private List<SinhVien> listSV;
    private HomeFrm home;
    private DataImp data = new DataImp();

    public AddSinhVienCNTT(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        home = (HomeFrm) parent;
        this.setLocationRelativeTo(null);
        listSV = new ArrayList<>();
        listSV = data.ReadFileJson(fileData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        txt_nhapMSV = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_nhapHoTen = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_nhapLopNC = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        txt_month = new javax.swing.JTextField();
        txt_year = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        comboQue = new javax.swing.JComboBox<>();
        LabeVL = new javax.swing.JLabel();
        txtvatly = new javax.swing.JTextField();
        LabelKNM = new javax.swing.JLabel();
        txtkinangmem = new javax.swing.JTextField();
        LabelOTM = new javax.swing.JLabel();
        txtOTOMAT = new javax.swing.JTextField();
        LabelQTM = new javax.swing.JLabel();
        txtQTM = new javax.swing.JTextField();
        LabelCSDL = new javax.swing.JLabel();
        txtCSDL = new javax.swing.JTextField();
        LabelTRIET = new javax.swing.JLabel();
        txtTRIET = new javax.swing.JTextField();
        LabelLAPTRINH = new javax.swing.JLabel();
        txtLAPTRINH = new javax.swing.JTextField();
        LabelTIN = new javax.swing.JLabel();
        txtTINHOC = new javax.swing.JTextField();
        LabelA3 = new javax.swing.JLabel();
        txtA3 = new javax.swing.JTextField();
        LabelA1 = new javax.swing.JLabel();
        txta1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel16.setText(" Mã sinh viên:");

        txt_nhapMSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhapMSVActionPerformed(evt);
            }
        });

        jLabel17.setText(" Họ và tên:");

        jLabel18.setText(" Lớp niên chế:");

        txt_nhapLopNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhapLopNCActionPerformed(evt);
            }
        });

        jLabel19.setText(" Date of birth:");

        jLabel20.setText(" Quê quán:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lý Sinh Viên CNTT");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\iconset4\\10207-man-student-light-skin-tone-icon-64.png")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\iconset4\\Actions-edit-delete-icon-16.png")); // NOI18N
        jButton2.setText("Hủy bỏ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        comboQue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Thái Bình", "Nghệ An", "Nam Định", "Đà Nẵng", "Quảng Ninh", "Vĩnh Phúc", "Ninh Bình" }));

        LabeVL.setText("Vật lí");

        txtvatly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvatlyActionPerformed(evt);
            }
        });

        LabelKNM.setText("Kĩ năng mềm");

        txtkinangmem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkinangmemActionPerformed(evt);
            }
        });

        LabelOTM.setText("Otomat");

        txtOTOMAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOTOMATActionPerformed(evt);
            }
        });

        LabelQTM.setText("Quản trị mạng");

        txtQTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQTMActionPerformed(evt);
            }
        });

        LabelCSDL.setText("Lí thuyết CSDL");

        txtCSDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSDLActionPerformed(evt);
            }
        });

        LabelTRIET.setText("Triết học");

        txtTRIET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTRIETActionPerformed(evt);
            }
        });

        LabelLAPTRINH.setText("Lập trình căn bản");

        txtLAPTRINH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLAPTRINHActionPerformed(evt);
            }
        });

        LabelTIN.setText("Tin học đại cương");

        txtTINHOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTINHOCActionPerformed(evt);
            }
        });

        LabelA3.setText("Toán cao cấp A3");

        txtA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA3ActionPerformed(evt);
            }
        });

        LabelA1.setText("Toán cao cấp A1");

        txta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txta1ActionPerformed(evt);
            }
        });

        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabeVL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelKNM))
                                .addComponent(LabelOTM))
                            .addComponent(LabelQTM, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelCSDL, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtvatly, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(txtkinangmem, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(txtOTOMAT, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(txtQTM)
                            .addComponent(txtCSDL))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(LabelTRIET))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelA3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LabelTIN)
                                        .addComponent(LabelLAPTRINH))
                                    .addComponent(LabelA1))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtA3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txta1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTINHOC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLAPTRINH, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(txtTRIET))))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboQue, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel16)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txt_month, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_nhapMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nhapHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txt_nhapLopNC)))
                    .addContainerGap(603, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelA1)
                                    .addComponent(txtvatly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabeVL))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtkinangmem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelKNM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelA3)
                                    .addComponent(txtA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtOTOMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelOTM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelTIN)
                                    .addComponent(txtTINHOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboQue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGap(64, 64, 64))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelQTM)
                                    .addComponent(LabelLAPTRINH)
                                    .addComponent(txtLAPTRINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCSDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelCSDL)
                                    .addComponent(LabelTRIET, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTRIET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nhapMSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txt_nhapHoTen))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txt_nhapLopNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(119, 119, 119)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nhapMSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhapMSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhapMSVActionPerformed

    private void txt_nhapLopNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhapLopNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhapLopNCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        SinhVien sv = new SinhVien();
        DsMonHoc vatly = new DsMonHoc();
        DsMonHoc kinangmem = new DsMonHoc();
        DsMonHoc otomat = new DsMonHoc();
        DsMonHoc qtm = new DsMonHoc();
        DsMonHoc csdl = new DsMonHoc();
        DsMonHoc a1 = new DsMonHoc();
        DsMonHoc a3 = new DsMonHoc();
        DsMonHoc tin = new DsMonHoc();
        DsMonHoc laptrinh = new DsMonHoc();
        DsMonHoc triet = new DsMonHoc();
        boolean isOK = true;
        boolean KiemTra = true;
        String name = txt_nhapHoTen.getText();
        String msv = txt_nhapMSV.getText();
        String lop = txt_nhapLopNC.getText();
        String que = comboQue.getSelectedItem().toString();

        if (name.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Họ tên không được để trống");
            isOK = false;
        } else if (msv.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Mã sinh viên không được để trống");
            isOK = false;
        } else if (lop.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Lớp niên chế không được để trống");
            isOK = false;
        }
        String reg = "^[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\\\s\\\\W|_ ]+";
        if (!name.matches("^[a-zA-Z]+")) {
            txt_nhapHoTen.setText("");
            JOptionPane.showMessageDialog(rootPane, "sai định dạng tên, nhập lại tên ");
            isOK = false;
        } else if (!msv.matches("^\\w{2}\\d{6}$")) {
            JOptionPane.showMessageDialog(rootPane, "Nhập sai định dạng MSV, ví dụ: CT040138");
            isOK = false;
        }
        if (msv.charAt(0) == 'C') {
            isOK = true;
        } else if (msv.charAt(0) != 'C') {
            JOptionPane.showMessageDialog(rootPane, "Nhập sai định dạng MSV, ví dụ: CT040138");
            isOK = false;
        }
        for (SinhVien q : listSV) {
            if (q.getMaSV().equalsIgnoreCase(msv)) {
                KiemTra = false;
            }
        }
        if (KiemTra == false) {
            JOptionPane.showMessageDialog(rootPane, "Trùng mã sinh viên! Xin nhập lại");
        }
        List<SinhVien> a = new ArrayList<>();
        if (isOK) {
            int day = 0, month = 0, year = 0;
            LocalDate date = null;
            sv.setMaSV(msv);
            sv.setHoTen(name);
            sv.setTenLopNC(lop);
            try {
                String d = txt_date.getText();
                String m = txt_month.getText();
                String y = txt_year.getText();

                day = Integer.parseInt(d);
                month = Integer.parseInt(m);
                year = Integer.parseInt(y);
                date = LocalDate.of(year, month, day);
            } catch (DateTimeException ex) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi " + ex);
                isOK = false;
            }
            List<DsMonHoc> l = new ArrayList<>();
            if (isOK) {
                String dateString = String.format("%d/%d/%d", day, month, year);
                sv.setNgaySinh(dateString);
                sv.setQueQuan(que);

                double vl = Double.parseDouble(txtvatly.getText());
                double knm = Double.parseDouble(txtkinangmem.getText());
                double td = Double.parseDouble(txtOTOMAT.getText());
                double qm = Double.parseDouble(txtQTM.getText());
                double csdL = Double.parseDouble(txtCSDL.getText());
                double trieT = Double.parseDouble(txtTRIET.getText());
                double c = Double.parseDouble(txtLAPTRINH.getText());
                double tinHOC = Double.parseDouble(txtTINHOC.getText());
                double A3 = Double.parseDouble(txtA3.getText());
                double A1 = Double.parseDouble(txta1.getText());

                if (vl < 0 || vl > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (knm < 0 || knm > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (td < 0 || td > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (qm < 0 || qm > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (csdL < 0 || csdL > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (trieT < 0 || trieT > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (c < 0 || c > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (tinHOC < 0 || tinHOC > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (A3 < 0 || A3 > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (A1 < 0 || A1 > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                }
                if (KiemTra == true) {
                    vatly.setDiemMH(Double.parseDouble(txtvatly.getText()));
                    vatly.setSoTC(2);
                    vatly.setTenMonHoc(LabeVL.getText());
                    l.add(vatly);
                    kinangmem.setDiemMH(Double.parseDouble(txtkinangmem.getText()));
                    kinangmem.setSoTC(2);
                    kinangmem.setTenMonHoc(LabelKNM.getText());
                    l.add(kinangmem);
                    otomat.setDiemMH(Double.parseDouble(txtOTOMAT.getText()));
                    otomat.setSoTC(2);
                    otomat.setTenMonHoc(LabelOTM.getText());
                    l.add(otomat);
                    qtm.setDiemMH(Double.parseDouble(txtQTM.getText()));
                    qtm.setSoTC(2);
                    qtm.setTenMonHoc(LabelQTM.getText());
                    l.add(qtm);
                    csdl.setDiemMH(Double.parseDouble(txtCSDL.getText()));
                    csdl.setSoTC(2);
                    csdl.setTenMonHoc(LabelCSDL.getText());
                    l.add(csdl);
                    a1.setDiemMH(Double.parseDouble(txta1.getText()));
                    a1.setSoTC(2);
                    a1.setTenMonHoc(LabelA1.getText());
                    l.add(a1);
                    a3.setDiemMH(Double.parseDouble(txtA3.getText()));
                    a3.setSoTC(2);
                    a3.setTenMonHoc(LabelA3.getText());
                    l.add(a3);
                    tin.setDiemMH(Double.parseDouble(txtTINHOC.getText()));
                    tin.setSoTC(2);
                    tin.setTenMonHoc(LabelTIN.getText());
                    l.add(tin);
                    laptrinh.setDiemMH(Double.parseDouble(txtLAPTRINH.getText()));
                    laptrinh.setSoTC(2);
                    laptrinh.setTenMonHoc(LabelLAPTRINH.getText());
                    l.add(laptrinh);
                    triet.setDiemMH(Double.parseDouble(txtTRIET.getText()));
                    triet.setSoTC(2);
                    triet.setTenMonHoc(LabelTRIET.getText());
                    l.add(triet);
                    sv.setDsMonHoc(l);
                    home.addSinhVien(sv);
                    JOptionPane.showMessageDialog(rootPane, "Thêm SV thành công");
                    this.dispose();
                }
            } else {
                a.remove(sv);
            }
        } else {
            a.remove(sv);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtvatlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvatlyActionPerformed
        double vatly = Double.parseDouble(txtvatly.getText());
        if (vatly < 0 || vatly > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtvatlyActionPerformed

    private void txtkinangmemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkinangmemActionPerformed
        double knm = Double.parseDouble(txtkinangmem.getText());
        if (knm < 0 || knm > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtkinangmemActionPerformed

    private void txtOTOMATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOTOMATActionPerformed
        double td = Double.parseDouble(txtOTOMAT.getText());
        if (td < 0 || td > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtOTOMATActionPerformed

    private void txtQTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQTMActionPerformed
        double qtm = Double.parseDouble(txtQTM.getText());
        if (qtm < 0 || qtm > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtQTMActionPerformed

    private void txtCSDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSDLActionPerformed
        double csdl = Double.parseDouble(txtCSDL.getText());
        if (csdl < 0 || csdl > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtCSDLActionPerformed

    private void txtTRIETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTRIETActionPerformed
        double triet = Double.parseDouble(txtTRIET.getText());
        if (triet < 0 || triet > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtTRIETActionPerformed

    private void txtLAPTRINHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLAPTRINHActionPerformed
        double c = Double.parseDouble(txtLAPTRINH.getText());
        if (c < 0 || c > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtLAPTRINHActionPerformed

    private void txtTINHOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTINHOCActionPerformed
        double tin = Double.parseDouble(txtTINHOC.getText());
        if (tin < 0 || tin > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtTINHOCActionPerformed

    private void txtA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA3ActionPerformed
        double a3 = Double.parseDouble(txtA3.getText());
        if (a3 < 0 || a3 > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtA3ActionPerformed

    private void txta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txta1ActionPerformed
        double a1 = Double.parseDouble(txta1.getText());
        if (a1 < 0 || a1 > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txta1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSinhVienCNTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSinhVienCNTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSinhVienCNTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSinhVienCNTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddSinhVienCNTT dialog = new AddSinhVienCNTT(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabeVL;
    private javax.swing.JLabel LabelA1;
    private javax.swing.JLabel LabelA3;
    private javax.swing.JLabel LabelCSDL;
    private javax.swing.JLabel LabelKNM;
    private javax.swing.JLabel LabelLAPTRINH;
    private javax.swing.JLabel LabelOTM;
    private javax.swing.JLabel LabelQTM;
    private javax.swing.JLabel LabelTIN;
    private javax.swing.JLabel LabelTRIET;
    private javax.swing.JComboBox<String> comboQue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JTextField txtA3;
    private javax.swing.JTextField txtCSDL;
    private javax.swing.JTextField txtLAPTRINH;
    private javax.swing.JTextField txtOTOMAT;
    private javax.swing.JTextField txtQTM;
    private javax.swing.JTextField txtTINHOC;
    private javax.swing.JTextField txtTRIET;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_month;
    private javax.swing.JTextField txt_nhapHoTen;
    private javax.swing.JTextField txt_nhapLopNC;
    private javax.swing.JTextField txt_nhapMSV;
    private javax.swing.JTextField txt_year;
    private javax.swing.JTextField txta1;
    private javax.swing.JTextField txtkinangmem;
    private javax.swing.JTextField txtvatly;
    // End of variables declaration//GEN-END:variables
}
