/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DataImp;
import java.io.File;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.DsMonHoc;
import model.SinhVien;

/**
 *
 * @author LaptopDT
 */
public class AddSinhVienATTT extends javax.swing.JDialog {

    private static final String currentDir = System.getProperty("user.dir");
    private static final String separator = File.separator;
    private static final String fileData = currentDir + separator + "data" + separator + "FileSV.json";
    private List<SinhVien> listSV;
    private HomeFrm home;
    private DataImp data = new DataImp();
    

    public AddSinhVienATTT(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        home = (HomeFrm) parent;
        this.setLocationRelativeTo(null);
        listSV = new ArrayList<>();
        listSV = data.ReadFileJson(fileData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_nhapMSV = new javax.swing.JTextField();
        txt_nhapHoTen = new javax.swing.JTextField();
        txt_nhapLopNC = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        txt_month = new javax.swing.JTextField();
        txt_year = new javax.swing.JTextField();
        LabeVL = new javax.swing.JLabel();
        txtvatly1 = new javax.swing.JTextField();
        LabelKNM = new javax.swing.JLabel();
        txtkinangmem1 = new javax.swing.JTextField();
        LabelTD = new javax.swing.JLabel();
        txtTD = new javax.swing.JTextField();
        LabelQTM = new javax.swing.JLabel();
        txtQTM1 = new javax.swing.JTextField();
        LabelCSDL = new javax.swing.JLabel();
        txtCSDL1 = new javax.swing.JTextField();
        LabelA1 = new javax.swing.JLabel();
        txtA1 = new javax.swing.JTextField();
        LabelA3 = new javax.swing.JLabel();
        txtA4 = new javax.swing.JTextField();
        LabelTIN = new javax.swing.JLabel();
        txtTINHOC1 = new javax.swing.JTextField();
        LabelLAPTRINH = new javax.swing.JLabel();
        txtLAPTRINH1 = new javax.swing.JTextField();
        LabelTRIET = new javax.swing.JLabel();
        txtTRIET1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        comboQue = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lý Sinh Viên ATTT");

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel16.setText(" Mã sinh viên:");

        jLabel17.setText(" Họ và tên:");

        jLabel18.setText(" Lớp niên chế:");

        jLabel19.setText(" Date of birth:");

        txt_nhapMSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhapMSVActionPerformed(evt);
            }
        });

        txt_nhapLopNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhapLopNCActionPerformed(evt);
            }
        });

        LabeVL.setText("Vật lí");

        txtvatly1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvatly1ActionPerformed(evt);
            }
        });

        LabelKNM.setText("Kĩ năng mềm");

        txtkinangmem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkinangmem1ActionPerformed(evt);
            }
        });

        LabelTD.setText("Thể chất");

        txtTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTDActionPerformed(evt);
            }
        });

        LabelQTM.setText("Quản trị mạng");

        txtQTM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQTM1ActionPerformed(evt);
            }
        });

        LabelCSDL.setText("Lí thuyết CSDL");

        txtCSDL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSDL1ActionPerformed(evt);
            }
        });

        LabelA1.setText("Toán cao cấp A1");

        txtA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA1ActionPerformed(evt);
            }
        });

        LabelA3.setText("Toán cao cấp A3");

        txtA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA4ActionPerformed(evt);
            }
        });

        LabelTIN.setText("Tin học đại cương");

        txtTINHOC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTINHOC1ActionPerformed(evt);
            }
        });

        LabelLAPTRINH.setText("Lập trình căn bản");

        txtLAPTRINH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLAPTRINH1ActionPerformed(evt);
            }
        });

        LabelTRIET.setText("Triết học");

        txtTRIET1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTRIET1ActionPerformed(evt);
            }
        });

        jLabel20.setText(" Quê quán:");

        comboQue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Thái Bình", "Nghệ An", "Nam Định", "Đà Nẵng", "Quảng Ninh", "Vĩnh Phúc", "Ninh Bình" }));
        comboQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboQueActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\iconset4\\Actions-edit-delete-icon-16.png")); // NOI18N
        jButton2.setText("Hủy bỏ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nhapMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_nhapHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nhapLopNC, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_month, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboQue, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(LabeVL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtvatly1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LabelKNM)
                                                    .addComponent(LabelTD))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtTD, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtkinangmem1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelA3)
                                            .addComponent(LabelA1)
                                            .addComponent(LabelTIN)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(LabelCSDL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCSDL1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelTRIET)
                                            .addComponent(LabelLAPTRINH)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(LabelQTM)
                                .addGap(18, 18, 18)
                                .addComponent(txtQTM1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtA1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtA4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLAPTRINH1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTINHOC1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTRIET1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nhapMSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabeVL)
                        .addComponent(txtvatly1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelA1)
                        .addComponent(txtA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_nhapHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_nhapLopNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboQue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelKNM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtkinangmem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelA3)
                            .addComponent(txtA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTD, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTIN)
                            .addComponent(txtLAPTRINH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelQTM)
                            .addComponent(txtQTM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelLAPTRINH)
                            .addComponent(txtTINHOC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCSDL)
                            .addComponent(txtCSDL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTRIET, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTRIET1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void txtTRIET1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTRIET1ActionPerformed
        double triet = Double.parseDouble(txtTRIET1.getText());
        if (triet < 0 || triet > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtTRIET1ActionPerformed

    private void txtLAPTRINH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLAPTRINH1ActionPerformed
        double c = Double.parseDouble(txtLAPTRINH1.getText());
        if (c < 0 || c > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtLAPTRINH1ActionPerformed

    private void txtTINHOC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTINHOC1ActionPerformed
        double tin = Double.parseDouble(txtTINHOC1.getText());
        if (tin < 0 || tin > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtTINHOC1ActionPerformed

    private void txtA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA4ActionPerformed
        double a3 = Double.parseDouble(txtA4.getText());
        if (a3 < 0 || a3 > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtA4ActionPerformed

    private void txtA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA1ActionPerformed
        double a1 = Double.parseDouble(txtA1.getText());
        if (a1 < 0 || a1 > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtA1ActionPerformed

    private void txtCSDL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSDL1ActionPerformed
        double csdl = Double.parseDouble(txtCSDL1.getText());
        if (csdl < 0 || csdl > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtCSDL1ActionPerformed

    private void txtQTM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQTM1ActionPerformed
        double qtm = Double.parseDouble(txtQTM1.getText());
        if (qtm < 0 || qtm > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtQTM1ActionPerformed

    private void txtTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTDActionPerformed
        double td = Double.parseDouble(txtTD.getText());
        if (td < 0 || td > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtTDActionPerformed

    private void txtkinangmem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkinangmem1ActionPerformed
        double knm = Double.parseDouble(txtkinangmem1.getText());
        if (knm < 0 || knm > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtkinangmem1ActionPerformed

    private void txtvatly1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvatly1ActionPerformed
        double vatly = Double.parseDouble(txtvatly1.getText());
        if (vatly < 0 || vatly > 10) {
            JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
        }
    }//GEN-LAST:event_txtvatly1ActionPerformed

    private void txt_nhapLopNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhapLopNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhapLopNCActionPerformed

    private void txt_nhapMSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhapMSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhapMSVActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        SinhVien sv = new SinhVien();
        DsMonHoc vatly = new DsMonHoc();
        DsMonHoc kinangmem = new DsMonHoc();
        DsMonHoc tc = new DsMonHoc();
        DsMonHoc qtm = new DsMonHoc();
        DsMonHoc csdl = new DsMonHoc();
        DsMonHoc a1 = new DsMonHoc();
        DsMonHoc a3 = new DsMonHoc();
        DsMonHoc tin = new DsMonHoc();
        DsMonHoc laptrinh = new DsMonHoc();
        DsMonHoc triet = new DsMonHoc();
        boolean isOK = true;
        boolean KiemTra = true;
        String name = txt_nhapHoTen.getText();
        String msv = txt_nhapMSV.getText();
        String lop = txt_nhapLopNC.getText();
        String que = comboQue.getSelectedItem().toString();

        if (name.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Họ tên không được để trống");
            isOK = false;
        } else if (msv.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Mã sinh viên không được để trống");
            isOK = false;
        } else if (lop.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Lớp niên chế không được để trống");
            isOK = false;
        }
        String reg = "^[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\\\s\\\\W|_ ]+";
        if (!name.matches("^[a-zA-Z]+")) {
            txt_nhapHoTen.setText("");
            JOptionPane.showMessageDialog(rootPane, "sai định dạng tên, nhập lại tên ");
            isOK = false;
        } else if (!msv.matches("^\\w{2}\\d{6}$")) {
            JOptionPane.showMessageDialog(rootPane, "Nhập sai định dạng MSV, ví dụ: AT160138");
            isOK = false;
        } else if (msv.charAt(0) != 'A' && msv.charAt(1) != 'T') {
            JOptionPane.showMessageDialog(rootPane, "Nhập sai định dạng MSV, ví dụ: AT160138");
            isOK = false;
        }
        for (SinhVien q : listSV) {
            if (q.getMaSV().equalsIgnoreCase(msv)) {
                KiemTra = false;
            }
        }
        if (KiemTra == false) {
            JOptionPane.showMessageDialog(rootPane, "Trùng mã sinh viên! Xin nhập lại");
        }
        List<SinhVien> a = new ArrayList<>();
        if (isOK) {
            int day = 0, month = 0, year = 0;
            LocalDate date = null;
            sv.setMaSV(msv);
            sv.setHoTen(name);
            sv.setTenLopNC(lop);
            try {
                String d = txt_date.getText();
                String m = txt_month.getText();
                String y = txt_year.getText();

                day = Integer.parseInt(d);
                month = Integer.parseInt(m);
                year = Integer.parseInt(y);
                date = LocalDate.of(year, month, day);
            } catch (DateTimeException ex) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi " + ex);
                isOK = false;
            }
            List<DsMonHoc> l = new ArrayList<>();
            if (isOK) {
                String dateString = String.format("%d/%d/%d", day, month, year);
                sv.setNgaySinh(dateString);
                sv.setQueQuan(que);

                double vl = Double.parseDouble(txtvatly1.getText());
                double knm = Double.parseDouble(txtkinangmem1.getText());
                double td = Double.parseDouble(txtTD.getText());
                double qm = Double.parseDouble(txtQTM1.getText());
                double csdL = Double.parseDouble(txtCSDL1.getText());
                double trieT = Double.parseDouble(txtTRIET1.getText());
                double c = Double.parseDouble(txtLAPTRINH1.getText());
                double tinHOC = Double.parseDouble(txtTINHOC1.getText());
                double A3 = Double.parseDouble(txtA4.getText());
                double A1 = Double.parseDouble(txtA1.getText());

                if (vl < 0 || vl > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (knm < 0 || knm > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (td < 0 || td > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (qm < 0 || qm > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (csdL < 0 || csdL > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (trieT < 0 || trieT > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (c < 0 || c > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (tinHOC < 0 || tinHOC > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (A3 < 0 || A3 > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                } else if (A1 < 0 || A1 > 10) {
                    JOptionPane.showMessageDialog(this, "0<= điểm <=10. Xin nhập lại");
                    KiemTra = false;
                }
                if (KiemTra == true) {
                    vatly.setDiemMH(Double.parseDouble(txtvatly1.getText()));
                    vatly.setSoTC(2);
                    vatly.setTenMonHoc(LabeVL.getText());
                    l.add(vatly);
                    kinangmem.setDiemMH(Double.parseDouble(txtkinangmem1.getText()));
                    kinangmem.setSoTC(2);
                    kinangmem.setTenMonHoc(LabelKNM.getText());
                    l.add(kinangmem);
                    tc.setDiemMH(Double.parseDouble(txtTD.getText()));
                    tc.setSoTC(2);
                    tc.setTenMonHoc(LabelTD.getText());
                    l.add(tc);
                    qtm.setDiemMH(Double.parseDouble(txtQTM1.getText()));
                    qtm.setSoTC(2);
                    qtm.setTenMonHoc(LabelQTM.getText());
                    l.add(qtm);
                    csdl.setDiemMH(Double.parseDouble(txtCSDL1.getText()));
                    csdl.setSoTC(2);
                    csdl.setTenMonHoc(LabelCSDL.getText());
                    l.add(csdl);
                    a1.setDiemMH(Double.parseDouble(txtA1.getText()));
                    a1.setSoTC(2);
                    a1.setTenMonHoc(LabelA1.getText());
                    l.add(a1);
                    a3.setDiemMH(Double.parseDouble(txtA4.getText()));
                    a3.setSoTC(2);
                    a3.setTenMonHoc(LabelA3.getText());
                    l.add(a3);
                    tin.setDiemMH(Double.parseDouble(txtTINHOC1.getText()));
                    tin.setSoTC(2);
                    tin.setTenMonHoc(LabelTIN.getText());
                    l.add(tin);
                    laptrinh.setDiemMH(Double.parseDouble(txtLAPTRINH1.getText()));
                    laptrinh.setSoTC(2);
                    laptrinh.setTenMonHoc(LabelLAPTRINH.getText());
                    l.add(laptrinh);
                    triet.setDiemMH(Double.parseDouble(txtTRIET1.getText()));
                    triet.setSoTC(2);
                    triet.setTenMonHoc(LabelTRIET.getText());
                    l.add(triet);
                    sv.setDsMonHoc(l);
                    home.addSinhVien(sv);
                    JOptionPane.showMessageDialog(rootPane, "Thêm SV thành công");
                    this.dispose();
                }
            } else {
                a.remove(sv);
            }
        } else {
            a.remove(sv);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void isEmpty() {
        txtA1.setText("");
        txtA4.setText("");
        txtCSDL1.setText("");
        txtLAPTRINH1.setText("");
        txtQTM1.setText("");
        txtTD.setText("");
        txtTINHOC1.setText("");
        txtTRIET1.setText("");
        txt_date.setText("");
        txt_month.setText("");
        txt_nhapHoTen.setText("");
        txt_nhapLopNC.setText("");
        txt_nhapMSV.setText("");
        txt_year.setText("");
        txtkinangmem1.setText("");
        txtvatly1.setText("");

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboQueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboQueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSinhVienATTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSinhVienATTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSinhVienATTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSinhVienATTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddSinhVienATTT dialog = new AddSinhVienATTT(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabeVL;
    private javax.swing.JLabel LabelA1;
    private javax.swing.JLabel LabelA3;
    private javax.swing.JLabel LabelCSDL;
    private javax.swing.JLabel LabelKNM;
    private javax.swing.JLabel LabelLAPTRINH;
    private javax.swing.JLabel LabelQTM;
    private javax.swing.JLabel LabelTD;
    private javax.swing.JLabel LabelTIN;
    private javax.swing.JLabel LabelTRIET;
    private javax.swing.JComboBox<String> comboQue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtA1;
    private javax.swing.JTextField txtA4;
    private javax.swing.JTextField txtCSDL1;
    private javax.swing.JTextField txtLAPTRINH1;
    private javax.swing.JTextField txtQTM1;
    private javax.swing.JTextField txtTD;
    private javax.swing.JTextField txtTINHOC1;
    private javax.swing.JTextField txtTRIET1;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_month;
    private javax.swing.JTextField txt_nhapHoTen;
    private javax.swing.JTextField txt_nhapLopNC;
    private javax.swing.JTextField txt_nhapMSV;
    private javax.swing.JTextField txt_year;
    private javax.swing.JTextField txtkinangmem1;
    private javax.swing.JTextField txtvatly1;
    // End of variables declaration//GEN-END:variables
}
